name: Test Psycopg
on: 
  workflow_dispatch:
jobs:
  TEST-PSYCOPG:
      runs-on: ubuntu-latest
      steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install psycopg
        run: pip install psycopg
      - name: test
        run: ls -l
